### ISSUE TITLE
basic authentication doesn't work

### ISSUE THREAD

**Issue by koooge** [takumakanari/embulk-input-http#5]
```
in:
  type: http
  url: http://localhost:8080/test.csv
  basic_auth:
    - user: MyUser
    - password: MyPassword
...
```

:cry: 

```
vagrant@vagrant-debian-jessie:/tmp/test$ embulk preview config.yml
2017-03-08 09:58:25.992 +0000: Embulk v0.8.18
2017-03-08 09:58:27.070 +0000 [INFO] (0001:preview): Loaded plugin embulk-input-http (0.0.15)
org.embulk.config.ConfigException: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.embulk.input.http.BasicAuthConfig out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1]
        at org.embulk.config.ModelManager.readObjectWithConfigSerDe(org/embulk/config/ModelManager.java:75)
        at org.embulk.config.DataSourceImpl.loadConfig(org/embulk/config/DataSourceImpl.java:220)
        at org.embulk.input.http.HttpFileInputPlugin.transaction(org/embulk/input/http/HttpFileInputPlugin.java:120)
        at org.embulk.spi.FileInputRunner.transaction(org/embulk/spi/FileInputRunner.java:65)
        at org.embulk.exec.SamplingParserPlugin.runFileInputSampling(org/embulk/exec/SamplingParserPlugin.java:34)
        at org.embulk.exec.PreviewExecutor.doPreview(org/embulk/exec/PreviewExecutor.java:96)
        at org.embulk.exec.PreviewExecutor.access$000(org/embulk/exec/PreviewExecutor.java:30)
        at org.embulk.exec.PreviewExecutor$1.run(org/embulk/exec/PreviewExecutor.java:70)
        at org.embulk.exec.PreviewExecutor$1.run(org/embulk/exec/PreviewExecutor.java:66)
        at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
        at org.embulk.exec.PreviewExecutor.preview(org/embulk/exec/PreviewExecutor.java:66)
        at org.embulk.EmbulkEmbed.preview(org/embulk/EmbulkEmbed.java:169)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:453)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:314)
        at RUBY.preview(/home/vagrant/.embulk/bin/embulk!/embulk/runner.rb:35)
        at RUBY.run(/home/vagrant/.embulk/bin/embulk!/embulk/command/embulk_run.rb:305)
        at RUBY.<main>(/home/vagrant/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2)
        at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:850)
        at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2976)
        at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:963)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
        at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
        at home.vagrant.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(home/vagrant/$_dot_embulk/bin/embulk/embulk/command/file:/home/vagrant/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
        at home.vagrant.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.<main>(file:/home/vagrant/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
        at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
        at org.jruby.Ruby.runScript(org/jruby/Ruby.java:834)
        at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:749)
        at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:767)
        at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:580)
        at org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
        at org.jruby.Main.internalRun(org/jruby/Main.java:313)
        at org.jruby.Main.run(org/jruby/Main.java:242)
        at org.jruby.Main.main(org/jruby/Main.java:204)
        at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.embulk.input.http.BasicAuthConfig out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:835)
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:831)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1229)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:165)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:144)
        at com.fasterxml.jackson.datatype.guava.deser.GuavaOptionalDeserializer.deserialize(GuavaOptionalDeserializer.java:98)
        at com.fasterxml.jackson.datatype.guava.deser.GuavaOptionalDeserializer.deserialize(GuavaOptionalDeserializer.java:18)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3534)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1894)
        at org.embulk.config.TaskSerDe$TaskDeserializer.deserialize(TaskSerDe.java:161)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3534)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1870)
        at org.embulk.config.ModelManager.readObjectWithConfigSerDe(ModelManager.java:72)
        at org.embulk.config.DataSourceImpl.loadConfig(DataSourceImpl.java:220)
        at org.embulk.input.http.HttpFileInputPlugin.transaction(HttpFileInputPlugin.java:120)
        at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:65)
        at org.embulk.exec.SamplingParserPlugin.runFileInputSampling(SamplingParserPlugin.java:34)
        at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:96)
        at org.embulk.exec.PreviewExecutor.access$000(PreviewExecutor.java:30)
        at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:70)
        at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:66)
        at org.embulk.spi.Exec.doWith(Exec.java:25)
        at org.embulk.exec.PreviewExecutor.preview(PreviewExecutor.java:66)
        at org.embulk.EmbulkEmbed.preview(EmbulkEmbed.java:169)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:453)
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:314)
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:46)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:205)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
        at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
        at org.jruby.Ruby.runInterpreter(Ruby.java:850)
        at org.jruby.Ruby.loadFile(Ruby.java:2976)
        at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:243)
        at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34)
        at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:885)
        at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:525)
        at org.jruby.runtime.load.LoadService.require(LoadService.java:396)
        at org.jruby.RubyKernel.requireCommon(RubyKernel.java:963)
        at org.jruby.RubyKernel.require19(RubyKernel.java:956)
        at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:383)
        at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
        at home.vagrant.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(file:/home/vagrant/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
        at home.vagrant.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/home/vagrant/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
        at org.jruby.ir.Compiler$1.load(Compiler.java:111)
        at org.jruby.Ruby.runScript(Ruby.java:834)
        at org.jruby.Ruby.runNormally(Ruby.java:749)
        at org.jruby.Ruby.runNormally(Ruby.java:767)
        at org.jruby.Ruby.runFromMain(Ruby.java:580)
        at org.jruby.Main.doRunFromMain(Main.java:425)
        at org.jruby.Main.internalRun(Main.java:313)
        at org.jruby.Main.run(Main.java:242)
        at org.jruby.Main.main(Main.java:204)
        at org.embulk.cli.Main.main(Main.java:23)

Error: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.embulk.input.http.BasicAuthConfig out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1]
```

**Comment by takumakanari** [comment]
Can you try following format, instead of array?

```yaml
  basic_auth:
    user: MyUser
    password: MyPassword
```

(sorry, it seems that documentation is wrong..)

**Comment by takumakanari** [comment]
also I fixed documentation:

https://github.com/takumakanari/embulk-input-http#use-basic-authentication

**Comment by koooge** [comment]
Oh thank you for fixing quickly :bowing_man:
